default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: falcon_development

test:
  <<: *default
  database: falcon_test


production:
  <<: *default
  database: falcon_production
  #username: falcon
  #password: <%= ENV['FALCON_DATABASE_PASSWORD'] %>
